# This workflow will run the distribution steps using node when a pull request is created or updated
# For more information see: https://docs.github.com/en/actions/using-workflows/about-workflows

name: PR Continuous Integration

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [develop]

jobs:
  dist:
    name: Continuous integration
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: 18
      - uses: pnpm/action-setup@v3
        with:
            version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test:ci

      - name: build
        run: pnpm build

      - name: Run E2E tests
        run: pnpm test:e2e
